{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "security-scan.namespace" . }}
  labels:
    {{- include "security-scan.labels" . | nindent 4 }}
{{- end }}
