{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "security-scan.namespace" . }}
  labels:
    {{- include "security-scan.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
